name: higlass-zarr-converters
channels:
  - conda-forge
  - bioconda
  - scottx611x
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - h5py
  - snakemake
  - scipy
  - jupyter
  - nb_conda
  - jq
  - pyyaml
  - tqdm
  - zarr
  - click
  - pip
  - pip:
    - negspy
    - pybbi>=0.2.3
